sudo: false

git:
  depth: 1

branches:
  only:
    - master

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: "11"
      script: npm run pretest
      env: CI=pretest
    - node_js: "11"
      script: npm run test-only
      env: CI=tests 11
    - node_js: "10"
      script: npm run test-only
      env: CI=tests 10
    - node_js: "8"
      script: npm run test-only
      env: CI=tests 8
    - node_js: "6"
      script: npm run test-only
      env: CI=tests 6

before_install:
  - npm install -g npm@latest
  - sudo apt-get install nasm
  - nvm --version
  - node --version
  - npm --version
